### PR TITLE
fix: flaky test_volume_metircs

### PR DESCRIPTION
**Pull request by chriscchien**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#8268

#### What this PR does / why we need it:

Test case flaky due to sometimes `delete_replica_processes` not make volume faulted. Add retry to make sure volume faulted before check Longhorn metric.

#### Special notes for your reviewer:

100 times test result on [master](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6687/ ) and [v1.6.x](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6689/)

#### Additional documentation or context

N/A

### CODE REVIEW

**Review by khushboo-rancher — COMMENTED** [review]
This change looks good to me as the objective here to assert the metrics displays correct value when volume is faulted. 
But I'm curious to know why the replica deletion sometimes couldn't make volume faulty, is it because after replica process deletion, volume rebuilt a replica quickly and test missed the faulty state?

**Comment by chriscchien** [comment]
> This change looks good to me as the objective here to assert the metrics displays correct value when volume is faulted. But I'm curious to know why the replica deletion sometimes couldn't make volume faulty, is it because after replica process deletion, volume rebuilt a replica quickly and test missed the faulty state?

I reproduced on v1.6.1, the volume actually became faulted but only remained in that state for approximately one second., so the test missed the faulty state.
So far I can not reproduce this on master, looks like the volume faluted state is longer enough for script to catch in master-head images.

volume state, the faluted state only kept in 1 second (58th second)
```bash
longhorn-system   longhorn-testvol-4todsu   v1            attached    healthy                  524288000   ip-172-31-47-19   56s
longhorn-system   longhorn-testvol-4todsu   v1            attached    faulted                  524288000   ip-172-31-47-19   58s
longhorn-system   longhorn-testvol-4todsu   v1            attached    faulted                  524288000   ip-172-31-47-19   58s
longhorn-system   longhorn-testvol-4todsu   v1            detaching   faulted                  524288000   ip-172-31-47-19   58s
longhorn-system   longhorn-testvol-4todsu   v1            detached    faulted                  524288000                     58s
longhorn-system   longhorn-testvol-4todsu   v1            detached    unknown                  524288000                     59s
```
replica state, replica error at 57th second, and the in 58 th second, all replica state changed from `error` to `stopped`
```bash
longhorn-system   longhorn-testvol-4todsu-r-170c0473   v1            error      ip-172-31-38-125   eb53d431-ec4c-4ee6-87e2-5eb9f1076969   instance-manager-6e3470166bf434c38a776985828ce286                                       57s
longhorn-system   longhorn-testvol-4todsu-r-53115c7b   v1            error      ip-172-31-47-19    9ffd107e-7370-4afe-a51b-3c755aba6cc9   instance-manager-b572a5dce18ad4940e21e75e84336ac8                                       57s
longhorn-system   longhorn-testvol-4todsu-r-170c0473   v1            error      ip-172-31-38-125   eb53d431-ec4c-4ee6-87e2-5eb9f1076969   instance-manager-6e3470166bf434c38a776985828ce286                                       57s
longhorn-system   longhorn-testvol-4todsu-r-170c0473   v1            stopped    ip-172-31-38-125   eb53d431-ec4c-4ee6-87e2-5eb9f1076969                                                                                           57s
longhorn-system   longhorn-testvol-4todsu-r-30912f28   v1            stopped    ip-172-31-41-161   beea6a3b-bb38-45d0-a673-849c0bfd4c2b                                                                                           57s
longhorn-system   longhorn-testvol-4todsu-r-30912f28   v1            stopped    ip-172-31-41-161   beea6a3b-bb38-45d0-a673-849c0bfd4c2b                                                                                           57s
longhorn-system   longhorn-testvol-4todsu-r-53115c7b   v1            error      ip-172-31-47-19    9ffd107e-7370-4afe-a51b-3c755aba6cc9   instance-manager-b572a5dce18ad4940e21e75e84336ac8                                       58s
longhorn-system   longhorn-testvol-4todsu-r-53115c7b   v1            stopped    ip-172-31-47-19    9ffd107e-7370-4afe-a51b-3c755aba6cc9                                                                                           58s
longhorn-system   longhorn-testvol-4todsu-r-170c0473   v1            stopped    ip-172-31-38-125   eb53d431-ec4c-4ee6-87e2-5eb9f1076969                                                                                           58s
longhorn-system   longhorn-testvol-4todsu-r-170c0473   v1            stopped    ip-172-31-38-125   eb53d431-ec4c-4ee6-87e2-5eb9f1076969                                                                                           58s
longhorn-system   longhorn-testvol-4todsu-r-53115c7b   v1            stopped    ip-172-31-47-19    9ffd107e-7370-4afe-a51b-3c755aba6cc9                                                                                           58s
longhorn-system   longhorn-testvol-4todsu-r-53115c7b   v1            stopped    ip-172-31-47-19    9ffd107e-7370-4afe-a51b-3c755aba6cc9                                                                                           58s
longhorn-system   longhorn-testvol-4todsu-r-170c0473   v1            stopped    ip-172-31-38-125   eb53d431-ec4c-4ee6-87e2-5eb9f1076969                                                                                           59s
longhorn-system   longhorn-testvol-4todsu-r-30912f28   v1            stopped    ip-172-31-41-161   beea6a3b-bb38-45d0-a673-849c0bfd4c2b                                                                                           59s
longhorn-system   longhorn-testvol-4todsu-r-53115c7b   v1            stopped    ip-172-31-47-19    9ffd107e-7370-4afe-a51b-3c755aba6cc9                                                                                           59s
longhorn-system   longhorn-testvol-4todsu-r-170c0473   v1            stopped    ip-172-31-38-125   eb53d431-ec4c-4ee6-87e2-5eb9f1076969                                                                                           59s
longhorn-system   longhorn-testvol-4todsu-r-30912f28   v1            stopped    ip-172-31-41-161   beea6a3b-bb38-45d0-a673-849c0bfd4c2b                                                                                           59s
longhorn-system   longhorn-testvol-4todsu-r-170c0473   v1            running    ip-172-31-38-125   eb53d431-ec4c-4ee6-87e2-5eb9f1076969   instance-manager-6e3470166bf434c38a776985828ce286   longhornio/longhorn-engine:v1.6.0   59s
longhorn-system   longhorn-testvol-4todsu-r-53115c7b   v1            stopped    ip-172-31-47-19    9ffd107e-7370-4afe-a51b-3c755aba6cc9                                                                                           59s
longhorn-system   longhorn-testvol-4todsu-r-30912f28   v1            running    ip-172-31-41-161   beea6a3b-bb38-45d0-a673-849c0bfd4c2b   instance-manager-9bd32cb9e168f5295409de0ae9ddf03d   longhornio/longhorn-engine:v1.6.0   60s
longhorn-system   longhorn-testvol-4todsu-r-53115c7b   v1            running    ip-172-31-47-19    9ffd107e-7370-4afe-a51b-3c755aba6cc9   instance-manager-b572a5dce18ad4940e21e75e84336ac8   longhornio/longhorn-engine:v1.6.0   60s
```

**Comment by khushboo-rancher** [comment]
@chriscchien Thanks for checking, what if we just increase the size of volume https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_metric.py#L289-L293 instead of looping and try to catch the faulty state. WDYT?

**Comment by chriscchien** [comment]
Updated and here is the test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6705/)

**Review by khushboo-rancher — APPROVED** [review]

**Comment by khushboo-rancher** [comment]
@mergify backport v1.6.x v1.5.x

**Pull request merged**
