### PR TITLE
Fix upgrade test

### PR DESCRIPTION
**Pull request by PhanLe1010**
Explanation:

* https://github.com/longhorn/longhorn/issues/6200#issuecomment-1610031861
* https://github.com/longhorn/longhorn/issues/6200#issuecomment-1610274243

longhorn/longhorn#6200

### CODE REVIEW

**Comment by PhanLe1010** [comment]
Test result https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4353/

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
cc @yangchiu @khushboo-rancher

**Comment by khushboo-rancher** [comment]
@PhanLe1010 t[est result link](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/514/) seems broken and did you abort the https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4353/ by mistake by any chance?

**Comment by PhanLe1010** [comment]
@khushboo-rancher https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4353/ uses the wrong Jenkin pipline so I aborted it. The one https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/514/ is waiting to be run in queue

**Comment by innobead** [comment]
@mergify backport v1.5.x

**Pull request merged**
