### PR TITLE
fix(support-bundle): test_support_bundle_purge

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/6320

### CODE REVIEW

**Comment by c3y1huang** [comment]
[Test result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4578/).

**Review by chriscchien — COMMENTED** [review]
LGTM and I used the code from this pull request to run the `test_support_bundle.py` file, all the test cases [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4582/testReport/tests/test_support_bundle/)

**Review by yangchiu — APPROVED** [review]
LGTM

**Comment by yangchiu** [comment]
@c3y1huang Do we still need this PR? Seems recently the test case doesn't fail anymore.

**Comment by c3y1huang** [comment]
> @c3y1huang Do we still need this PR? Seems recently the test case doesn't fail anymore.

I see no harm in asserting the status code. WDYT?

**Comment by yangchiu** [comment]
Agree. And checking the request's response before accessing the payload is more reasonable.

**Pull request merged**
