### PR TITLE
test: find backup should also wait until backup volume is synced

### PR DESCRIPTION
**Pull request by yangchiu**
#### Which issue(s) this PR fixes:

Issue https://github.com/longhorn/longhorn/issues/7543 https://github.com/longhorn/longhorn/issues/7959

#### What this PR does / why we need it:

Sync the modification in https://github.com/longhorn/longhorn-tests/pull/1668 to other `find_backup_volume` function occurrences in the test code.

### CODE REVIEW

**Comment by yangchiu** [comment]
@ChanYiLin Could you help to review this? Thank you!

**Review by innobead — APPROVED** [review]

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@yangchiu see if need to backport.

**Comment by yangchiu** [comment]
@Mergify backport v1.6.x v1.5.x

**Comment by yangchiu** [comment]
@mergify backport v1.4.x

**Pull request merged**
