### PR TITLE
doc: Add a test for the longhorn manager NPE issue

### PR DESCRIPTION
**Pull request by shuo-wu**
Longhorn/longhorn#3484

### CODE REVIEW

**Comment by khushboo-rancher** [comment]
I think, we can add this test in the integration test rather than in the manual.

**Review by khushboo-rancher — COMMENTED** [review]
I think, we can add this test in the integration test rather than manual.

**Comment by shuo-wu** [comment]
> I think, we can add this test in the integration test rather than manual.

The operations in this test are not invalid use cases in the real world... I don't think we need to put it in Longhorn nightly integration test plan.

**Review by innobead — APPROVED** [review]
LGTM but this is more like chaos testing instead of e2e testing. 

I think it's fine to have it in the manual regression for now.

**Pull request merged**
