### PR TITLE
Add test case test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly

### PR DESCRIPTION
**Pull request by chriscchien**
Add test case test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly

ref: [6373](https://github.com/longhorn/longhorn/issues/6373)

### CODE REVIEW

**Comment by yangchiu** [comment]
Is it possible to have a test result of it?

**Comment by chriscchien** [comment]
> Is it possible to have a test result of it?

Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4679/testReport/tests/test_kubernetes/) on pipeline

**Comment by khushboo-rancher** [comment]
@mergify backport v1.5.x

**Comment by khushboo-rancher** [comment]
@mergify backport v1.4.x

**Pull request merged**
