### PR TITLE
Transfer CSI snapshot test steps from github comment to test doc

### PR DESCRIPTION
**Pull request by cchien816**
Signed-off-by: Chris Chien <chris.chien@suse.com>

From https://github.com/longhorn/longhorn/issues/3639

Transfer CSI snapshot test steps from github [comment](https://github.com/longhorn/longhorn/issues/2534#issuecomment-1010508714) to manual test doc

cc @PhanLe1010

### CODE REVIEW

**Comment by cchien816** [comment]
Hi @khushboo-rancher ,

I move location of test case and add test scenario `Concurrent backup creation & deletion `, thank you

**Comment by PhanLe1010** [comment]
Thanks @cchien816 and @khushboo-rancher!

We have agreed on the keywords. The backend is merged. The test steps are updated in the [GitHub comment](https://github.com/longhorn/longhorn/issues/2534#issuecomment-1010508714) to use the new keyword.

@cchien816 Could you:
* Update this PR with the new keywords as in the [GitHub comment](https://github.com/longhorn/longhorn/issues/2534#issuecomment-1010508714)
 * Run this test case 1 more time with the new keywords

**Review by khushboo-rancher — DISMISSED** [review]
Thanks @cchien816 

LGTM

It has 5 commits, can you club them together in 1 commit before merging?

**Review by PhanLe1010 — DISMISSED** [review]
LGTM 

But need to squash the commits as Khushboo mentioned

**Comment by cchien816** [comment]
Squashed 5 commits together in 1 commit

cc @khushboo-rancher , @PhanLe1010

**Review by kaxing — APPROVED** [review]

**Review by khushboo-rancher — APPROVED** [review]

**Pull request merged**
