### PR TITLE
Remove deprecated mkfs-ext4-parameters setting

### PR DESCRIPTION
**Pull request by ejweber**
https://github.com/longhorn/longhorn/issues/5849

### CODE REVIEW

**Comment by ejweber** [comment]
I've tried a number of times to test these changes in Jenkins, but I can't currently get a working version of `master-head` deployed (https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3719/). I have a dev cluster running with a longhorn-manager build from my `4914-remove-mkfs-ext4-parameters-setting`, and select test cases (including the one called out in https://github.com/longhorn/longhorn/issues/5849) are passing.

```
eweber@laptop:~/longhorn-tests/manager/integration> kubectl logs -f longhorn-test
Defaulted container "longhorn-test" out of: longhorn-test, longhorn-test-report
============================= test session starts ==============================
platform linux -- Python 3.9.16, pytest-5.3.1, py-1.11.0, pluggy-0.13.1 -- /usr/bin/python3.9
cachedir: .pytest_cache
rootdir: /integration, inifile: pytest.ini
plugins: repeat-0.9.1, order-1.0.1
collecting ... collected 395 items / 394 deselected / 1 selected

test_node.py::test_node_disk_update PASSED                               [100%]

================ 1 passed, 394 deselected in 370.19s (0:06:10) =================
eweber@laptop:~/longhorn-tests/manager/integration> 
```

**Review by PhanLe1010 — APPROVED** [review]
LGTM

I understand that `create_host_disk` is making a disk on host for Longhorn to schedule volume's replica. This disk just needs to be xfs or ext4. It doesn't need to be formatted using the  setting `mkfs-ext4-parameters` value. The setting `mkfs-ext4-parameters` is to format the fs of Longhorn volume not the disk on the host. So it is even ok to be removed from the previous longhorn-test version too (though this is unnecessary).

**Comment by ejweber** [comment]
I ran a suite of tests against `master-head` in my local cluster. After fixing an environment issue, these four tests are failing:

```
test_basic.py::test_expansion_canceling FAILED                           [ 50%]
test_basic.py::test_expansion_with_scheduling_failure FAILED             [ 52%]
test_migration.py::test_migration_with_rebuilding_replica FAILED         [ 86%]
test_migration.py::test_migration_with_restore_volume[s3] FAILED         [ 88%]
```

The top two are explained by https://github.com/longhorn/longhorn/issues/5860. I am still looking for an explanation for the bottom two.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
Merge until @ejweber clarify the failed cases.

**Comment by ejweber** [comment]
The two unexplained failures seem to have been flakes. I am having no trouble getting them to pass in my cluster now. I suggest we merge.

```
test_migration.py::test_migration_with_failed_replica PASSED             [100%]
test_migration.py::test_migration_with_rebuilding_replica PASSED         [100%]
```

**Pull request merged**
