### PR TITLE
Revert pr-1221 since revert back to `softerr`/`soft` mode in https://…

### PR DESCRIPTION
**Pull request by roger-ryao**
…github.com/longhorn/longhorn/issues/6655

This reverts commit https://github.com/longhorn/longhorn-tests/pull/1221/commits/14236563ce64077ab374d0fe5d2916fadb25d8c4

Ref: https://github.com/longhorn/longhorn/issues/6838

### CODE REVIEW

**Comment by innobead** [comment]
@roger-ryao Good follow up.

**Review by yangchiu — CHANGES_REQUESTED** [review]
@roger-ryao This PR hasn't been merged yet but the test case still passes. Do you know why?

**Comment by roger-ryao** [comment]
> @roger-ryao This PR hasn't been merged yet but the test case still passes. Do you know why?

Hi @yangchiu 
The `share-manger` pod might be gone and no longer come back in `soft-mode`, but we haven't encountered this scenario during our daily runs.

**Review by yangchiu — APPROVED** [review]
LGTM

**Pull request merged**
