### PR TITLE
Add test_dr_volume_with_last_backup_deletion() skeleton

### PR DESCRIPTION
**Pull request by shuo-wu**
longhorn/longhorn#1380

### CODE REVIEW

**Comment by yasker** [comment]
> Do we also need to add a test case for the second scenario mentioned in the original issue?

We only have one cluster in the test framework, so we won't able to address the Scenario #2.

**Comment by sowmyav27** [comment]
@yasker The second scenario does not need 2 clusters.

**Comment by yasker** [comment]
@sowmyav27 you're right, I misread it.

**Comment by yasker** [comment]
@sowmyav27 In fact, the scenario #2 is the same as scenario #1. create b2 and delete it before DR volume can restore it. From Longhorn’s perspective, the last backup is empty and no extra backup in the backupstore, so it’s the same.

**Comment by shuo-wu** [comment]
@sowmyav27 
I tried to write an integration test for this scenario https://github.com/longhorn/longhorn/issues/1380/#issuecomment-632147058.
but the situation of step 9 was impossible for the single cluster environment: 
Once the 2nd backup creation complete, the field `lastBackup` of both volumes will be updated immediately.

**Comment by yasker** [comment]
LGTM. @sowmyav27 ?

**Pull request merged**
