### PR TITLE
test: using the same set of longhorn resources throughout the 2 stage upgrade test

### PR DESCRIPTION
**Pull request by yangchiu**
#### Which issue(s) this PR fixes:

Issue https://github.com/longhorn/longhorn/issues/9306

#### What this PR does / why we need it:

using the same set of longhorn resources throughout the 2 stage upgrade test

### CODE REVIEW

**Review by roger-ryao — APPROVED** [review]
LGTM

**Comment by yangchiu** [comment]
@mergify backport v1.7.x

**Comment by yangchiu** [comment]
@mergify backport v1.6.x

**Comment by chriscchien** [comment]
@mergify backport v1.6.x

**Pull request merged**
