### PR TITLE
modify security group to allow udp connection for longhorn webhooks

### PR DESCRIPTION
**Pull request by meldafrawi**
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@suse.com>

### CODE REVIEW

**Review by innobead — COMMENTED** [review]
LGTM, but I would like to where to find out UDP traffic is needed for webhook.

**Comment by jenting** [comment]
> LGTM, but I would like to where to find out UDP traffic is needed for webhook.

+1, I'll double-check the code as well.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
Merged first, but will rever if needed after @jenting figures out the root cause later.

**Comment by innobead** [comment]
@meldafrawi said

while debugging the issue,
i suspected that it is a networking issue, opened all communications to/from controller node, tests passed
tried to open only TCP connections, the tests fail again.
that narrowed it down to UDP communication, but i couldn't find which port is required for that communication.

**Pull request merged**
