### PR TITLE
fix(pipeline): upgrade SLES kernel version

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/6076

### CODE REVIEW

**Comment by c3y1huang** [comment]
@yangchiu could you help to trigger a private regression `-k test_csi_mount_volume_online_expansion --count 5` using the repo from this PR? It seems there isn't an available option for me to do this in the pipeline.

**Comment by c3y1huang** [comment]
Test results: wip
- https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-upgrade-tests-sles-amd64/226/

**Comment by c3y1huang** [comment]
- https://github.com/longhorn/longhorn/issues/6089
  - https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-upgrade-tests-sles-amd64/228/
  - https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-upgrade-tests-sles-amd64/230/
  - https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-upgrade-tests-sles-amd64/231/

**Comment by c3y1huang** [comment]
Close this due to this is a known Kernel issue and has already been resolved upstream.

**Comment by innobead** [comment]
So the best practice for users, whatever kernel they are using, it's better to ensure they upgrade to the latest stable version.

**Pull request closed without merging**
