### PR TITLE
test: fix flaky test case test_offline_node

### PR DESCRIPTION
**Pull request by yangchiu**
#### Which issue(s) this PR fixes:

Issue https://github.com/longhorn/longhorn/issues/7463

#### What this PR does / why we need it:

Correctly pass resource_suffix as aws instance filter parameter.

### CODE REVIEW

**Review by khushboo-rancher — APPROVED** [review]

**Comment by yangchiu** [comment]
@Mergify backport v1.6.x v1.5.x v1.4.x

**Comment by yangchiu** [comment]
@mergify backport v1.6.x v1.5.x v1.4.x

**Comment by yangchiu** [comment]
@mergify backport v1.5.x

**Comment by yangchiu** [comment]
@mergify backport v1.6.x v1.5.x v1.4.x

**Pull request merged**
