### PR TITLE
test(robot): fix Test Migration Confirm for v2 volume

### PR DESCRIPTION
**Pull request by chriscchien**
#### What this PR does / why we need it:

fix `Test Migration Confirm` for v2 volume

#### Additional documentation or context

Test result

v1.8.x v2 data engine : https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2308/
v1.8.x v1 data engine : https://ci.longhorn.io/job/private/job/longhorn-e2e-test/2310/

## Summary by CodeRabbit

- **New Features**
	- Updated migration criteria by removing checks for engine and replica differences during migration success.

- **Bug Fixes**
	- Adjusted the migration test cases to reflect the change in expected outcomes, removing the assertion that migration should succeed.

### CODE REVIEW

**Review by yangchiu — CHANGES_REQUESTED** [review]
Suggest removing `Volume ${volume_id} migration should succeed` step from the test case directly.

Also, too many typos in the description https://github.com/longhorn/longhorn-tests/pull/2224#issue-2757262230.

**Comment by chriscchien** [comment]
> Suggest removing `Volume ${volume_id} migration should succeed` step from the test case directly.
> 
> Also, too many typos in the description [#2224 (comment)](https://github.com/longhorn/longhorn-tests/pull/2224#issue-2757262230).

Updated, I also deleted keyword `Volume ${volume_id} migration should succeed` because it is nowhere to use now.

**Review by yangchiu — APPROVED** [review]
LGTM

**Comment by yangchiu** [comment]
@Mergify backport v1.8.x

**Pull request merged**
