### PR TITLE
Set a longer backup wait interval for backup wait function

### PR DESCRIPTION
**Pull request by shuo-wu**

### CODE REVIEW

**Comment by yasker** [comment]
Reason for the change?

**Comment by shuo-wu** [comment]
Some of the recent nightly test failures is caused by the short backup wait interval.

**Comment by yasker** [comment]
Why do we need a longer backup completion wait time now? Is our backup speed slowed down compared to previous versions?

**Comment by c3y1huang** [comment]
This seems already resolve in https://github.com/longhorn/longhorn-tests/commit/b8fbb2d67bfa5714bbda85095ec1a40aab49ea2b .

**Comment by yasker** [comment]
The original issue has been fixed in https://github.com/longhorn/longhorn-tests/pull/409

**Pull request closed without merging**
