### PR TITLE
Test for Snapshot prune feature & snapshot revert improvement

### PR DESCRIPTION
**Pull request by shuo-wu**
Longhorn/longhorn#3613
Longhorn/longhorn#3748

### CODE REVIEW

**Review by cchien816 — APPROVED** [review]

**Comment by shuo-wu** [comment]
I just added one more data chunk writing after the expansion, which would help verify the expanded part won't affect the snapshot prune.

**Comment by shuo-wu** [comment]
PR update:
1. Verify that the snapshot prune always happens after all snapshot coalescing & deletion done.
2. Add backing image related tests.

**Review by yangchiu — DISMISSED** [review]

**Review by cchien816 — DISMISSED** [review]

**Comment by shuo-wu** [comment]
Add a manual test for retrying purge the snapshots marked as Removed

**Review by cchien816 — APPROVED** [review]

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
