### PR TITLE
Add test case test_drain_with_block_for_eviction_success

### PR DESCRIPTION
**Pull request by chriscchien**
Add test case `test_drain_with_block_for_eviction_success`

ref: [7521](https://github.com/longhorn/longhorn/issues/7521)

#### Which issue(s) this PR fixes:

Issue #7521

#### What this PR does / why we need it:

Test case only have skeleton

#### Special notes for your reviewer:

10 times test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6271/testReport/tests/test_node/)

#### Additional documentation or context

N/A

### CODE REVIEW

**Comment by chriscchien** [comment]
Add test case `test_drain_with_block_for_eviction_if_contains_last_replica_success`

10 times test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6292/testReport/tests/test_node/)

**Comment by chriscchien** [comment]
Test case have potential fail rate if the drain node have backup store located, need invetigate after https://github.com/longhorn/longhorn/issues/8004
```
error: unable to drain node "ip-10-0-2-211" due to error:cannot delete Pods declare no controller (use --force to override): default/longhorn-test-minio, continuing command...
There are pending nodes to be drained:
```

**Comment by chriscchien** [comment]
Add test case `test_drain_with_block_for_eviction_failure` and test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6414/testReport/tests/test_node/) here

Need test again after https://github.com/longhorn/longhorn-tests/pull/1744 merged

**Comment by chriscchien** [comment]
10 times test of below test cases all [passed](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/6448/testReport/tests/test_node/)
- test_drain_with_block_for_eviction_failure
- test_drain_with_block_for_eviction_success
- test_drain_with_block_for_eviction_if_contains_last_replica_success

**Review by yangchiu — APPROVED** [review]
LGTM

**Comment by chriscchien** [comment]
@mergify backport v1.6.x

**Pull request merged**
