### PR TITLE
integration: Add test_filesystem_trim

### PR DESCRIPTION
**Pull request by shuo-wu**
Longhorn/longhorn#836

### CODE REVIEW

**Comment by innobead** [comment]
@shuo-wu PR check failed

**Comment by shuo-wu** [comment]
https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2815/

**Review by khushboo-rancher — DISMISSED** [review]
LGTM, just need to resolve the conflict and then we should be good to merge.

**Comment by shuo-wu** [comment]
Conflict resolved

**Review by khushboo-rancher — APPROVED** [review]

**Comment by yangchiu** [comment]
@Mergifyio backport v1.4.x

**Pull request merged**
