### PR TITLE
 Fix flaky test case test_recovery_from_im_deletion

### PR DESCRIPTION
**Pull request by chriscchien**
Fix flaky test case `test_recovery_from_im_deletion`

Immediately exec into deployment pod after instance-manager pod delete and recreate ready some how will get `kubernetes.client.exceptions.ApiException` make test case flaky.

Add a retry mechanism to fetch deployment pod data to avoid test case directly fail

Master branch test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4381/) 5/10 failure
PR code test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4382/) 0/10 failure

ref [6222](https://github.com/longhorn/longhorn/issues/6222)

### CODE REVIEW

**Review by yangchiu — CHANGES_REQUESTED** [review]
Conflicts need to be resolved first before being merged.

**Comment by chriscchien** [comment]
> Conflicts need to be resolved first before being merged.

Updated!, thanks

**Review by yangchiu — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@chriscchien Please go ahead to use mergify to backport. @yangchiu can help review and merge the backport PRs.

**Comment by chriscchien** [comment]
@mergify backport v1.5.x

**Comment by chriscchien** [comment]
@mergify backport v1.4.x v1.3.x

**Pull request merged**
