### PR TITLE
storage-network: do not reset setting

### PR DESCRIPTION
**Pull request by c3y1huang**
https://github.com/longhorn/longhorn/issues/2285

### CODE REVIEW

**Comment by innobead** [comment]
@c3y1huang Is this ready for review?

**Comment by c3y1huang** [comment]
Note: We currently don't have a pipeline to test the storage network. This PR works for a cluster with a pre-configured storage-network setting.

**Comment by innobead** [comment]
@c3y1huang Please help backport to 1.3 and 1.2. Thanks.

**Comment by c3y1huang** [comment]
> @c3y1huang Please help backport to 1.3 and 1.2. Thanks.

Storage-network is a 1.3 feature, we don't need to backport this to 1.2.x.

**Comment by innobead** [comment]
> > @c3y1huang Please help backport to 1.3 and 1.2. Thanks.
> 
> Storage-network is a 1.3 feature, we don't need to backport this to 1.2.x.

You are right! :)

**Pull request merged**
