### PR TITLE
update minio ssl certificate for tests

### PR DESCRIPTION
**Pull request by meldafrawi**
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>

REF: https://github.com/longhorn/longhorn/issues/2286

### CODE REVIEW

**Review by joshimoo — APPROVED** [review]
LGTM, I am assuming these are the certificates that I posted from the engine integration tests?
Can you also open a PR against longhorn/longhorn to update the `backupstore.yaml` there as well.
https://github.com/longhorn/longhorn/tree/master/deploy/backupstores

**Comment by yasker** [comment]
@joshimoo https://github.com/longhorn/longhorn/tree/master/deploy/backupstores is a copy of the backupstores directory here. We should have the release v1.1.1 out of door before end of April so we can sync it up during the release process.

**Comment by joshimoo** [comment]
@yasker thanks for clarifying I didn't remember whether it was synced or not :)

**Comment by meldafrawi** [comment]
Just for reference, the new cert end date is 

```
Certificate:
        Validity
            Not Before: Apr 27 23:00:11 2020 GMT
            Not After : Apr  3 23:00:11 2120 GMT

```

**Pull request merged**
