### PR TITLE
Add test skeleton to verify the setting taint toleration in some additional scenarios

### PR DESCRIPTION
**Pull request by PhanLe1010**
Add test skeleton to verify the setting taint toleration in some additional scenarios:

1. Two tolerations with the same key but different operator/effect/value
2. Toleration's key contains substring `kubernetes.io`
3. Special toleration case

longhorn/longhorn#1977

### CODE REVIEW

**Comment by shuo-wu** [comment]
There is an existing test `test_setting_toleration`. Can you check if that is available for you first?

**Comment by PhanLe1010** [comment]
@shuo-wu Thanks
Yeah, there is a `test_setting_toleration `. This PR test different scenarios. I renamed the test to  test_setting_toleration_extra` to avoid confusion

**Review by shuo-wu — DISMISSED** [review]

**Comment by yasker** [comment]
Drone is failing. Also waiting for the manager part.

**Comment by PhanLe1010** [comment]
Fixed the flake8 error

**Review by yasker — APPROVED** [review]

**Pull request merged**
