### PR TITLE
fix(robot): skip kubelet terminated pod in get_workload_pods

### PR DESCRIPTION
**Pull request by c3y1huang**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn#8550

#### What this PR does / why we need it:

https://github.com/longhorn/longhorn/issues/8550#issuecomment-2109276522

### CODE REVIEW

**Review by derekbit — APPROVED** [review]
LGTM

**Review by roger-ryao — APPROVED** [review]
LGTM

**Review by yangchiu — DISMISSED** [review]
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/573/ failed.
Need to clarify if it's affected by this PR.

**Comment by c3y1huang** [comment]
> https://ci.longhorn.io/job/private/job/longhorn-e2e-test/573/ failed. Need to clarify if it's affected by this PR.

It should be already addressed with the recent force-push commits.

**Comment by c3y1huang** [comment]
Test result: https://ci.longhorn.io/job/private/job/longhorn-e2e-test/575/

**Review by yangchiu — APPROVED** [review]
https://ci.longhorn.io/job/private/job/longhorn-e2e-test/575/ passed.

**Pull request merged**
