### PR TITLE
Ignore the error caused by listing the deleting backups

### PR DESCRIPTION
**Pull request by shuo-wu**
https://github.com/longhorn/longhorn/issues/826

### CODE REVIEW

**Comment by yasker** [comment]
Can we fix the error instead?

**Comment by shuo-wu** [comment]
1. It's an error caused by the intermediate status of backup volumes. I don't think there is a big impact on the Longhorn system.
2. We cannot find a simple way to fix the error that caused by listing and deleting the backups of the same volume simultaneously.

**Comment by yasker** [comment]
Longhorn system itself is OK but it's an unexpected error to the API and user.

I think we should put this on hold and think more about it.

**Comment by shuo-wu** [comment]
We can fix the error caused by listing backup volumes only and deleting the backups simultaneously, which leads to this test failure. But the case I mentioned above is unavoidable.

**Pull request closed without merging**
