### PR TITLE
move backupstore creation after longhorn setup

### PR DESCRIPTION
**Pull request by meldafrawi**
Signed-off-by: Mohamed Eldafrawi <mohamed.eldafrawi@rancher.com>

### CODE REVIEW

**Comment by yasker** [comment]
Reason? What if we want to run backup cases for upgrade test in the future?

**Comment by yasker** [comment]
OK, just saw the reason. We can create the namespace beforehand then.

**Comment by meldafrawi** [comment]
minio backupstore is deployed to `longhorn-system` namespace.

**Comment by meldafrawi** [comment]
@yasker updated.

**Pull request merged**
