### PR TITLE
Use longhorn repo for backup store creation

### PR DESCRIPTION
**Pull request by chriscchien**
#### Which issue(s) this PR fixes:

Issue longhorn/longhorn/issues/8004

#### What this PR does / why we need it:

Use manifest in longhorn repo for backup store creation instead of longhorn-test repo

#### Special notes for your reviewer:

Test passed on local by create backup store from longhorn [repo](https://github.com/longhorn/longhorn/tree/master/deploy/backupstores) and then perform core tests

image

#### Additional documentation or context

N/A

### CODE REVIEW

**Comment by roger-ryao** [comment]
Hi @chriscchien 
    I think we also need to update https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/README.md?plain=1#L21 in this pull request. What do you think?

**Comment by chriscchien** [comment]
> Hi @chriscchien I think we also need to update https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/README.md?plain=1#L21 in this pull request. What do you think?

Updated!

**Review by yangchiu — APPROVED** [review]
LGTM

**Comment by yangchiu** [comment]
@Mergify backport v1.6.x v1.5.x v1.4.x

**Pull request merged**
