### PR TITLE
Fix flaky case : test_node_eviction_soft_anti_affinity

### PR DESCRIPTION
**Pull request by chanow816**
Signed-off-by: Chris Chien <chris.chien@suse.com>
Origin from [tests.test_node.test_node_eviction_soft_anti_affinity](https://ci.longhorn.io/job/public/job/master/job/ubuntu/job/amd64/job/longhorn-tests-ubuntu-amd64-nfs/12/testReport/junit/tests/test_node/test_node_eviction_soft_anti_affinity/) and can reproduce on my local environment.

All fail happened at step 13, when replicas stop at node 2 and start to schedule on node 1 and node 3, at very few rate volume.robustness become **False** make script assert error and flaky.

In my observation, this volume.robustness become **False** behavior stay at few seconds and did not really effect replica schedule on node 1 and node 3, so I would like to change wait_for_replica_scheduled in common.py let the for loop work on volume and check in the neat end step.
```
    1. Disable scheduling on node 3.
    2. Create pv, pvc, pod with volume of 2 replicas.
    3. Write some data and get the checksum.
    7. Set 'Eviction Requested' to 'true' and disable scheduling on node 1.
    8. Set 'Replica Node Level Soft Anti-Affinity' to 'true'.
    9. Check volume 'healthy' and wait for replicas running on node 2
    Case #2: node 2 to node 1, 3 eviction
    10. Enable scheduling on node 1 and 3.
    11. Set 'Replica Node Level Soft Anti-Affinity' to 'false'.
    12. Set 'Eviction Requested' to 'true' and disable scheduling on node 2.
    13. Check volume 'healthy' and wait for replicas running on node 1 and 3.
    14. Check volume data checksum.
```

### CODE REVIEW

**Review by innobead — CHANGES_REQUESTED** [review]
I would suggest to use `wait_for_volume_healthy` before the flaky step 13 instead of modifying `wait_for_replica_scheduled` because you will change the original pre-condition of `wait_for_replica_scheduled` which is the volume is healy.

**Comment by chanow816** [comment]
Hi @innobead, 
In our current design, there already exist `wait_for_volume_healthy` before `wait_for_replica_scheduled` just like you mentioned.
To avoid modify `wait_for_replica_scheduled` , I add argument `chk_vol_healthy=False` when calling it.
Because we checked volume healthy before, and in the end we still check replicas running on node 1 and node 3.

**Review by innobead — APPROVED** [review]
LGTM, it's ok for now, but it is still a little confusing why the volume is not healthy in a short time sometimes.

**Comment by innobead** [comment]
@chanow816 Please backport to 1.2.x and 1.1.x.

**Pull request merged**
