### PR TITLE
ci: implement rancher chart install/upgrade regression test pipeline

### PR DESCRIPTION
**Pull request by yangchiu**
ci: implement rancher chart install/upgrade regression test pipeline

For https://github.com/longhorn/longhorn/issues/3987 https://github.com/longhorn/longhorn/issues/5936

Signed-off-by: Yang Chiu <yang.chiu@suse.com>

### CODE REVIEW

**Review by khushboo-rancher — CHANGES_REQUESTED** [review]
Structure and approach looks good to me. Few points as below 
1. Can we add an option to accept rancher version, if not present install the latest one.
2. Can we add an option to choose installation of Longhorn app with mirrored image or longhornio image?

**Comment by khushboo-rancher** [comment]
Also, can we avoid using selenium to get the Rancher access keys and instead use kubeconfig or API?

**Comment by yangchiu** [comment]
> Also, can we avoid using selenium to get the Rancher access keys and instead use kubeconfig or API?

Currently working on this.

**Comment by yangchiu** [comment]
> > Also, can we avoid using selenium to get the Rancher access keys and instead use kubeconfig or API?
> 

This has been refined. We don't need to use selenium anymore. Instead, directly calling HTTP request to get access key and secret just like https://github.com/rancher/rancher/blob/release/v2.8/tests/integration/suite/conftest.py#L103.

**Review by khushboo-rancher — APPROVED** [review]

**Comment by khushboo-rancher** [comment]
@yangchiu Could you please trigger the CI and share the result. Thank you

**Comment by yangchiu** [comment]
> @yangchiu Could you please trigger the CI and share the result. Thank you

fresh install: https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/3/
upgrade test: https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/4/
2 stage upgrade: https://ci.longhorn.io/job/private/job/longhorn-rancher-chart-test/6/

**Pull request merged**
