### PR TITLE
Add test case test_csi_volumesnapshot_restore_on_demand_backing_image, test_csi_volumesnapshot_backing_image_basic

### PR DESCRIPTION
**Pull request by chriscchien**
Add test case `test_csi_volumesnapshot_restore_on_demand_backing_image`
ref: [6231](https://github.com/longhorn/longhorn/issues/6231)

Add test case `test_csi_volumesnapshot_backing_image_basic`
ref: [6293](https://github.com/longhorn/longhorn/issues/6293)

Add test case `test_csi_volumesnapshot_restore_pre_provision_backing_image`
ref: [6309](https://github.com/longhorn/longhorn/issues/6309)

Signed-off-by: Chris <chris.chien@suse.com>

Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4643/testReport/tests/test_csi_snapshotter/)

### CODE REVIEW

**Review by ChanYiLin — APPROVED** [review]

**Review by yangchiu — APPROVED** [review]
LGTM

**Review by khushboo-rancher — APPROVED** [review]

**Comment by khushboo-rancher** [comment]
@mergify backport v1.5.x

**Comment by khushboo-rancher** [comment]
@chriscchien Does it require 1.4.x backport?

**Comment by chriscchien** [comment]
> @chriscchien Does it require 1.4.x backport?

No. this feature not introduced in v1.4.x ([ref](https://github.com/longhorn/longhorn/issues/6266#issuecomment-1628531596))

**Pull request merged**
