### PR TITLE
Add manual tests and automated skeletons for Replica Disk Soft Anti-Affinity

### PR DESCRIPTION
**Pull request by ejweber**
longhorn/longhorn#3823

### CODE REVIEW

**Comment by ejweber** [comment]
I have addressed most (hopefully all) of the drone complaints in an amend, but GitHub is currently experiencing PR related problems and my changes aren't reflected here. Will check back later.

**Comment by innobead** [comment]
@khushboo-rancher @yangchiu review this. Thanks.

**Review by khushboo-rancher — APPROVED** [review]
Thanks @ejweber, LGTM

nit: We can add one more test case in the manual test cases to verify the existing replicas on same disks can be scheduled properly after the upgrade as below.
```
**Given** An outdated Longhorn cluster with one volume having 3 replicas on same disk

**When** The cluster is upgraded

*And* Replica rebuilding is triggered by crashing the instance manager

*Then* All the replica should get scheduled on different disks.
```

**Comment by khushboo-rancher** [comment]
Merging this as this is good enough, we can take care of the minor [suggestion](https://github.com/longhorn/longhorn-tests/pull/1522#pullrequestreview-1643068857) while testing this

**Pull request merged**
