### PR TITLE
test(manual): update Physical node reboot

### PR DESCRIPTION
**Pull request by chriscchien**
longhorn/longhorn-8567

#### Which issue(s) this PR fixes:

Issue https://github.com/longhorn/longhorn/issues/8567

#### What this PR does / why we need it:

In v1.6.2 and master, reboot workload volume node, the workload not 100% attached to the origin node after the rebooted node ready.

Update test case for only check volume healthy and data correct.

### CODE REVIEW

**Review by yangchiu — CHANGES_REQUESTED** [review]
Does the behavior conflict with the [`single replica node down` test case](https://github.com/longhorn/longhorn-tests/blob/master/e2e/tests/test_cases/single_replica_node_down.robot) you just implemented? I believe it checks if the volume is attached to a specific node.

**Comment by chriscchien** [comment]
> Does the behavior conflict with the [`single replica node down` test case](https://github.com/longhorn/longhorn-tests/blob/master/e2e/tests/test_cases/single_replica_node_down.robot) you just implemented? I believe it checks if the volume is attached to a specific node.

In that test case, there is only one replica exist, it is different from this test case.

**Comment by yangchiu** [comment]
I'm not familiar with the behavior. Can other team members confirm it? Many thanks! cc @longhorn/qa @longhorn/dev @derekbit

**Review by roger-ryao — APPROVED** [review]
LGTM

**Review by yangchiu — APPROVED** [review]

**Pull request merged**
