### PR TITLE
Add manual test plan to verify that CSI components' images are updated

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#1642

### CODE REVIEW

**Comment by PhanLe1010** [comment]
Will add negative test case

**Comment by PhanLe1010** [comment]
Added negative test cases

**Comment by yasker** [comment]
Let's put this into the pre-release test since deploying the same image shouldn't trigger the redeploy even Longhorn is upgraded.

**Comment by PhanLe1010** [comment]
I moved it to `pre-release`

**Review by yasker — APPROVED** [review]
LGTM. Waiting for the manager part to be checked in.

**Comment by yasker** [comment]
Not sure why this test case was missed. cc @PhanLe1010

**Comment by PhanLe1010** [comment]
I am not sure neither. May be we were waiting and forgot 
> LGTM. Waiting for the manager part to be checked in.

**Pull request merged**
