### PR TITLE
test(robot): increase disk size to prevent running out of space during long-running tests

### PR DESCRIPTION
**Pull request by yangchiu**
#### Which issue(s) this PR fixes:

Issue N/A

#### What this PR does / why we need it:

increase disk size to prevent running out of space during long-running tests

### CODE REVIEW

**Comment by khushboo-rancher** [comment]
Where do we run our negative test in general, sles?

**Review by chriscchien — APPROVED** [review]
LGTM

**Comment by yangchiu** [comment]
> Where do we run our negative test in general, sles?

yes.

**Comment by khushboo-rancher** [comment]
What's the reason behind increasing the size of disks of all the pipelines?

**Comment by yangchiu** [comment]
> What's the reason behind increasing the size of disks of all the pipelines?

Created https://github.com/longhorn/longhorn/issues/9149 for it.

**Pull request merged**
