### PR TITLE
Update the integration tests and add a manual test for the backing image upload

### PR DESCRIPTION
**Pull request by shuo-wu**
longhorn/longhorn#2404

Signed-off-by: Shuo Wu <shuo.wu@suse.com>

### CODE REVIEW

**Comment by khushboo-rancher** [comment]
Few below doubts - 
1. On uploading the image, will the file be uploaded to all the nodes?
2. How does setting `Backing Image Cleanup Wait Interval` gonna work now? Will it delete the backing image files from all the nodes except one after the interval time passes by?

**Comment by shuo-wu** [comment]
> Few below doubts -
> 
> 1. On uploading the image, will the file be uploaded to all the nodes?
> 2. How does setting `Backing Image Cleanup Wait Interval` gonna work now? Will it delete the backing image files from all the nodes except one after the interval time passes by?

1. Longhorn will pick up **one** random schedulable node to store the uploaded file
2. For the setting, it works but there is one exception for the uploaded backing image: It won't delete all ready files now. Instead, it will retain one random ready file and remove other files.

**Review by khushboo-rancher — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@shuo-wu is this updated?

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
