### PR TITLE
Update the release tests

### PR DESCRIPTION
**Pull request by khushboo-rancher**
1. Deleted the tests which are already automated.
2. Added few tests for the release testing

Signed-off-by: Khushboo <fnu.khushboo@suse.com>

### CODE REVIEW

**Review by innobead — APPROVED** [review]
For each newly created case, if it's driven from a bug, suggest addigng next to the test case as a reference.

**Comment by innobead** [comment]
@longhorn/qa have we tested the larget volume test case w/ and w/o snapshot checksum?

**Comment by yangchiu** [comment]
> @longhorn/qa have we tested the larget volume test case w/ and w/o snapshot checksum?

The `Checksum enabled large volume with multiple rebuilding` test case in this PR is included in our v1.4.0 release testing plan, and I've tested it.

**Comment by innobead** [comment]
Thanks, @yangchiu !

**Pull request merged**
