### PR TITLE
Add automation for mirroring the quay.io/openshift/origin-oauth-proxy image

### PR DESCRIPTION
**Pull request by PhanLe1010**
longhorn/longhorn#8329

### CODE REVIEW

**Review by yangchiu — APPROVED** [review]
LGTM

**Comment by PhanLe1010** [comment]
Jenklin CI run failed with error:
```
time="2024-04-10T02:44:40Z" level=fatal msg="trying to reuse blob sha256:97da74cc6d8fa5d1634eb1760fd1da5c6048619c264c23e62d75f3bf6b8ef5c4 at destination: checking whether a blob sha256:97da74cc6d8fa5d1634eb1760fd1da5c6048619c264c23e62d75f3bf6b8ef5c4 exists in docker.io/longhornio/openshift-origin-oauth-proxy: requested access to the resource is denied"
===
Failed copying image for longhornio/openshift-origin-oauth-proxy
===
	arm64 NOT FOUND
	arm NOT FOUND
	s390x NOT FOUND
	Writing manifest list to docker.io/longhornio/openshift-origin-oauth-proxy:4.14
sha256:1ece77d14a685ef2397c3a327844eea45ded00c95471e9e333e35ef3860b1895
ERROR: httpReadSeeker: failed open: server message: insufficient_scope: authorization failed
===
Failed copying image for longhornio/openshift-origin-oauth-proxy
```

Ref: https://ci.longhorn.io/job/private/job/mirror-csi-images/21/console

Could you help? @yangchiu

**Comment by PhanLe1010** [comment]
@yangchiu mentioned that we need to create the docker hub repo first docker.io/longhornio/openshift-origin-oauth-proxy

Could you help us? @innobead

**Comment by yangchiu** [comment]
@innobead Probably need your help to create the `openshift-origin-oauth-proxy` repo first and make sure it's writable. Thank you!

**Comment by innobead** [comment]
@PhanLe1010 @yangchiu done!

**Comment by PhanLe1010** [comment]
Thanks a lot @yangchiu @innobead ! The CI run successful now https://ci.longhorn.io/job/private/job/mirror-csi-images/22/console

**Pull request merged**
