### PR TITLE
Add case test_csi_block_volume_online_expansion

### PR DESCRIPTION
**Pull request by chriscchien**
Test [result](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/3600/)

Ref [5820](https://github.com/longhorn/longhorn/issues/5820)

Signed-off-by: Chris <chris.chien@suse.com>

### CODE REVIEW

**Comment by khushboo-rancher** [comment]
@chriscchien Can you please link the ticket this is associated with?
@yangchiu Could you please help with the review?

**Review by yangchiu — COMMENTED** [review]
According to the test skeleton:
```
3. Generate `test_data` in a directory the volume is not mounted on.
4. Copy the `test data` to the volume block device asynchronously.
```
Do we actually do this in this implementation?

**Comment by chriscchien** [comment]
> According to the test skeleton:
> 
> ```
> 3. Generate `test_data` in a directory the volume is not mounted on.
> 4. Copy the `test data` to the volume block device asynchronously.
> ```
> 
> Do we actually do this in this implementation?

I merged step 3 and 4 by using `dd` command with suprogress.pipe(), while the pipe is still executing, do volume expansion mentioned in step 5

It is because if I first generate test-data by `dd if=/dev/urandom of=/tmp/test-data bs=1M count=2500` which mentioned in step 3 and then immediately copy test-data into volume device by `dd if=/tmp/test-data of=/dev/<volume>`, the data in `/dev/<volume>` is depend on the time when I start to copy, not the whole test-data.

**Comment by yangchiu** [comment]
> > I merged step 3 and 4 by using `dd` command with suprogress.pipe(), while the pipe is still executing, do volume expansion mentioned in step 5
> 
> > It is because if I first generate test-data by `dd if=/dev/urandom of=/tmp/test-data bs=1M count=2500` which mentioned in step 3 and then immediately copy test-data into volume device by `dd if=/tmp/test-data of=/dev/<volume>`, the data in `/dev/<volume>` is depend on the time when I start to copy, not the whole test-data.


If the implementation is different from the skeleton, can we modify the skeleton to make them consistent?

**Comment by chriscchien** [comment]
> > > I merged step 3 and 4 by using `dd` command with suprogress.pipe(), while the pipe is still executing, do volume expansion mentioned in step 5
> > 
> > 
> > > It is because if I first generate test-data by `dd if=/dev/urandom of=/tmp/test-data bs=1M count=2500` which mentioned in step 3 and then immediately copy test-data into volume device by `dd if=/tmp/test-data of=/dev/<volume>`, the data in `/dev/<volume>` is depend on the time when I start to copy, not the whole test-data.
> 
> If the implementation is different from the skeleton, can we modify the skeleton to make them consistent?

Hi @yangchiu,updated.

**Review by yangchiu — APPROVED** [review]
LGTM

**Review by khushboo-rancher — APPROVED** [review]

**Pull request merged**
