### PR TITLE
ci: use more cost-effective ec2 instance type

### PR DESCRIPTION
**Pull request by yangchiu**
#### Which issue(s) this PR fixes:

Issue https://github.com/longhorn/longhorn/issues/7957

#### What this PR does / why we need it:

use more cost-effective ec2 instance type

### CODE REVIEW

**Review by innobead — APPROVED** [review]
LGTM.

Let's make sure our document also have the right info with distro testing. 

https://longhorn.io/docs/1.6.0/best-practices/#operating-system, we mentioned 9.3 for RHEL and Oracle, so the exact version should be 9.1?

**Comment by yangchiu** [comment]
> 
> https://longhorn.io/docs/1.6.0/best-practices/#operating-system, we mentioned 9.3 for RHEL and Oracle, so the exact version should be 9.1?
> 

@chriscchien @roger-ryao Can we get the regression test report of RHEL and Oracle when we did the release testing `v1.6.0` to confirm this? I'm unable to find the links. Thanks.

**Comment by roger-ryao** [comment]
> > https://longhorn.io/docs/1.6.0/best-practices/#operating-system, we mentioned 9.3 for RHEL and Oracle, so the exact version should be 9.1?
> 
> @chriscchien @roger-ryao Can we get the regression test report of RHEL and Oracle when we did the release testing `v1.6.0` to confirm this? I'm unable to find the links. Thanks.

After checking the Jenkins job history, I found that the Oracle version is [9.3](https://ci.longhorn.io/job/public/job/master/job/oracle/job/amd64/job/longhorn-tests-oracle-amd64/19/parameters/)  and RHEL is [9.3](https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/170/parameters/) .I could not update the Qase v1.6.0 test report anymore. I will update the distribution version in the test result next time.

**Comment by innobead** [comment]
Thanks @roger-ryao .

@yangchiu this PR was merged. Can you update the distro version to 9.3 to Oracle and RHEL?

**Pull request merged**
