### PR TITLE
Script to generate test data

### PR DESCRIPTION
**Pull request by chriscchien**
Add generate test data script 

- test_tools/gen_data/clean.sh
   - clean workload
- test_tools/gen_data/config.yaml
   - config
- test_tools/gen_data/deployment.yaml  
   - template
- test_tools/gen_data/README.md
- test_tools/gen_data/run.sh
- test_tools/gen_data/statefulset.yaml    
   - template

`./run.sh`
`./clean.sh`
 
ref: [6665](https://github.com/longhorn/longhorn/issues/6665)

### CODE REVIEW

**Review by yangchiu — CHANGES_REQUESTED** [review]
Is it necessary to have dependencies on the existing pytest code? Can't we use shell scripts to simulate what we usually do in manual testing? WDYT

**Comment by chriscchien** [comment]
> Is it necessary to have dependencies on the existing pytest code? Can't we use shell scripts to simulate what we usually do in manual testing? WDYT

There are many ways to achieve the goal and looks like you already have shell script to do the same thing, could you share the code for some inspiration? many thanks.

**Comment by chriscchien** [comment]
Updated to shell script

**Review by yangchiu — APPROVED** [review]
LGTM

**Pull request merged**
